import { ReduxProvider } from "@/providers/ReduxProvider";
import "./globals.css";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Arvi",
  description: "Generated by Arvi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
