import { ReduxProvider } from "@/providers/ReduxProvider";
import "./globals.css";
import { Metadata } from "next";
import { AuthProvider } from "@/providers/AuthProvider";
export const metadata: Metadata = {
  title: "Arvi | Drive. Share. Connect.",
  description: "Generated by Arvi",
  icons: {
    icon: "/logo.svg",
    shortcut: "/logo.svg",
    apple: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <AuthProvider>{children}</AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
